name: cartoswiss
description: An always growing Swiss map
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  get_it: ^7.2.0
  dafluta: ^4.2.0
  url_strategy: ^0.2.0

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 

dev_dependencies:
  dalocale: ^2.4.2
  daassets: ^1.3.2
  daunused: ^1.3.0
  dapublock: ^1.0.1
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true